#!/usr/bin/env perl
#  dt
#  =  Copyright 2013 Xiong Changnian <xiong@cpan.org>   =
#  = Free Software = Artistic License 2.0 = NO WARRANTY =

use 5.016002;   # 5.16.2    # 2012  # __SUB__
use strict;
use warnings;
use version; our $VERSION = qv('v0.0.0');

# Core modules
use lib 'lib';

# CPAN modules
use Getopt::Complete(           # Shell completion and options parsing

    '>new'      => [                # set
        '>module'   => [                # tool
            '<>'        => undef,           # bare argument
        ],
    ],
    '>list'     => [
        '>modules'  => [
            '<>'        => undef,           # bare argument
        ],
    ],
    
); ## getopt

# Project module
use Devel::Toolbox;             # Simple custom project tool management

# Alternate uses
use Devel::Comments '###';                                               #~
#~ use Devel::Comments '###', ({ -file => 'debug.log' });                   #~

## use
#============================================================================#

### @ARGV
### %ARGS

__END__

